### ISSUE TITLE
"CoderCrunch" saytında maraqlı testlər işləyə bilərsən

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [MehdiCef/FoundationProject#7]
[**CoderCrunch**](https://www.codercrunch.com/quiz/search?skill=javascript) saytından istədiyin dilə uyğun (sol tərəfdən seçmək olur, çoxlu seçim var) test işləyə bilərsən. Sonda da nəticəni göstərir (neçə düz, neçə səhv etdiyini). Maraqlı ola biləcəyini düşündüm. İşləyib özünü yoxlaya bilərsən.

**Comment by MehdiCef** [comment]
> [**CoderCrunch**](https://www.codercrunch.com/quiz/search?skill=javascript) saytından istədiyin dilə uyğun (sol tərəfdən seçmək olur, çoxlu seçim var) test işləyə bilərsən. Sonda da nəticəni göstərir (neçə düz, neçə səhv etdiyini). Maraqlı ola biləcəyini düşündüm. İşləyib özünü yoxlaya bilərsən.

Təşəkkürlər.
